# Alacritty configuration file

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
bold = { family = "MesloLGS Nerd Font", style = "Bold" }
italic = { family = "MesloLGS Nerd Font", style = "Italic" }

[window]
opacity = 0.7
blur = true

[terminal.shell]
program = "/usr/bin/zsh"
