#!/bin/bash
# no-attribution/check: PreToolUse hook for git/gh write commands.
# Blocks any commit/PR/issue/release whose command string contains AI
# attribution (Co-Authored-By, "Generated with Claude Code", session
# URLs, Anthropic email, GitHub Action review markers, etc).
#
# Scoped via `if` filters in settings.json so it only spawns on commands
# that actually write public text — every other Bash call is free.
#
# Install: registered under hooks.PreToolUse[matcher=Bash] in settings.json
# Exit codes:
#   0 — allow
#   2 — blocking error; stderr is fed back to Claude as a tool error

set -euo pipefail

cmd=$(jq -r '.tool_input.command')

# All variants of AI attribution Claude Code is known to emit, plus
# kernel.org-style alternatives and generic "AI-assisted/generated" phrasing.
forbidden='co-authored-by:|co-author:|🤖|generated with claude|generated by claude|claude\.ai/code/session|noreply@anthropic\.com|anthropic\.com|<!-- *claude-|assisted-by: *claude|\bai[- ]?assist|\bai[- ]?generated|\bwith help from claude'

if echo "$cmd" | grep -qiE "$forbidden"; then
  cat >&2 <<'EOF'
BLOCKED: this user's git history contains zero AI attribution. The
proposed commit/PR/issue/release contains one of:

  - Co-Authored-By: or Co-author: trailer
  - 🤖 robot emoji
  - "Generated with Claude Code" / "Generated by Claude"
  - claude.ai/code/session URL
  - noreply@anthropic.com or anthropic.com
  - <!-- claude-code-* --> GitHub Action marker
  - "Assisted-by: Claude" trailer
  - "AI-assisted" / "AI-generated" / "with help from Claude" phrasing

Rewrite the message with zero AI attribution and retry. Do not add any
trailer, footer, or marker indicating AI authorship.
EOF
  exit 2
fi

exit 0
