#!/bin/bash
# no-attribution/session-start: SessionStart hook.
# Injects a factual policy reminder into the session at start so Claude
# doesn't try to add AI attribution to commits/PRs in the first place.
#
# Phrased as project policy (not imperative) to avoid tripping Claude's
# prompt-injection defenses. The check.sh hook is the enforcement
# backstop if this reminder is ignored.
#
# Plain stdout is injected into context as a <system-reminder>.

cat <<'EOF'
This user's git history contains zero AI attribution. Commits and PR/issue/release bodies authored in this environment never include:

  - Co-Authored-By: or Co-author: trailers
  - "🤖 Generated with Claude Code" / "Generated by Claude" footers
  - claude.ai/code/session deep-link URLs
  - noreply@anthropic.com or anthropic.com references
  - "Assisted-by: Claude" trailers
  - "AI-assisted" / "AI-generated" / "with help from Claude" phrasing

Author commits, PRs, and issue comments as if written by hand. The settings.json `attribution` field is empty for this reason. A PreToolUse hook enforces this policy and will reject any git commit, gh pr, gh issue, or gh release command whose message contains AI attribution.
EOF
